// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/expense-tracker/App.tsx": () => import("../components/mockups/expense-tracker/App.tsx"),
  "./components/mockups/expense-tracker/DogAnimation.tsx": () => import("../components/mockups/expense-tracker/DogAnimation.tsx")
};
